CREATE TABLE CUSTOMER (CUSTOMER_ID INT PRIMARY KEY, FIRST_NAME VARCHAR(20), MIDDLE_NAME VARCHAR(20), LAST_NAME VARCHAR(20), EMAIL VARCHAR(30));
CREATE TABLE TELEPHONE_TYPE(TELEPHONE_TYPE_ID INT PRIMARY KEY, TELEPHONE_TYPE_CD CHAR(1), TELEPHONE_TYPE_TEXT VARCHAR(20));
CREATE TABLE TELEPHONE (TELEPHONE_ID INT PRIMARY KEY, TELEPHONE_TYPE_ID INT REFERENCES TELEPHONE_TYPE, CUSTOMER_ID INT REFERENCES CUSTOMER, TELEPHONE_NUMBER CHAR(12));
CREATE TABLE ADDRESS_TYPE (ADDRESS_TYPE_ID INT PRIMARY KEY, ADDRESS_TYPE_CODE CHAR(1), ADDRESS_TYPE_TEXT VARCHAR(20));
CREATE TABLE US_STATE(US_STATE_ID INT PRIMARY KEY, US_STATE_CD CHAR(2) NOT NULL, US_STATE_NM VARCHAR(30) NOT NULL);
CREATE TABLE "APP"."US_CITY"(US_CITY_ID int PRIMARY KEY NOT NULL,US_CITY_NM varchar(30),ZIP char(5),US_STATE_ID int);
ALTER TABLE US_CITY ADD CONSTRAINT SQL080413034555231 FOREIGN KEY (US_STATE_ID)
REFERENCES US_STATE(US_STATE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
CREATE INDEX SQL080413034555231 ON US_CITY(US_STATE_ID);
CREATE UNIQUE INDEX SQL080413034555230 ON US_CITY(US_CITY_ID);

CREATE TABLE ADDRESS (ADDRESS_ID INT PRIMARY KEY, ADDRESS_TYPE_ID INT REFERENCES ADDRESS_TYPE, CUSTOMER_ID INT REFERENCES CUSTOMER,
ADDR_LINE_1 VARCHAR(100), ADDR_LINE_2 VARCHAR(100), CITY VARCHAR (100), US_STATE_ID INT REFERENCES US_STATE, ZIP CHAR(5));
CREATE TABLE CUSTOMER_ORDER(CUSTOMER_ORDER_ID INT PRIMARY KEY, CUSTOMER_ID INT REFERENCES CUSTOMER, ORDER_NUMBER VARCHAR (10), ORDER_DESCRIPTION VARCHAR(200));
CREATE TABLE ITEM(ITEM_ID INT PRIMARY KEY, ITEM_NUMBER VARCHAR(10), ITEM_SHORT_DESC VARCHAR(100), ITEM_LONG_DESC VARCHAR(500));
CREATE TABLE ORDER_ITEM(CUSTOMER_ORDER_ID INT REFERENCES CUSTOMER_ORDER, ITEM_ID INT REFERENCES ITEM);
CREATE TABLE APP_USER(APP_USER_ID INT PRIMARY KEY, USER_NAME VARCHAR(10), PASSWORD VARCHAR (15));
CREATE TABLE USER_ROLE(ROLE_ID INT PRIMARY KEY, ROLE_NAME VARCHAR(10));
CREATE TABLE APP_USER_ROLE(APP_USER_ID INT REFERENCES APP_USER, USER_ROLE_ID INT REFERENCES USER_ROLE);
CREATE TABLE "APP"."SEQUENCE"
(
   SEQ_NAME varchar(50),
   SEQ_COUNT decimal(15)
)
;